### ISSUE TITLE
For cross-platform use npm package 'shx - shx find' instead unix util 'find'

### ISSUE THREAD

**Issue by sergeymakoveev** [facebookincubator/fbt#37]
For cross-platform do not use unix util `find`
You can use npm package [shx](https://www.npmjs.com/package/shx)
'yarn manifest' failed in windows

```
PS Z:\sources\react\fbt\demo-app> yarn manifest
yarn run v1.12.3
$ babel-node ../transform/babel-plugin-fbt/bin/manifest --src src
�� ������ 䠩�: '*$FbtEnum.js'
child_process.js:645
    throw err;
    ^

Error: Command failed: find . -type f -iname '*$FbtEnum.js'
�� ������ 䠩�: '*$FbtEnum.js'

    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
    at Object.<anonymous> (Z:\sources\react\fbt\transform\babel-plugin-fbt\bin\manifest.js:76:3)
    at Module._compile (module.js:653:30)
    at Module._compile (Z:\sources\react\fbt\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader (Z:\sources\react\fbt\node_modules\pirates\lib\index.js:88:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS Z:\sources\react\fbt\demo-app>
```

**Comment by jrwats** [comment]
Perfect! I was contemplating adding the slower `glob()` and `fs.readFile(...)`.  I'll see if we can add this today
