### ISSUE TITLE
[babel-plugin-fbt] Invalid deploy, fbjs is missing in dependencies

### ISSUE THREAD

**Issue by retyui** [facebookincubator/fbt#66]
### In repo:

https://github.com/facebookincubator/fbt/blob/2add25c108c601a11088c10e5c8f808b8ad62897/transform/babel-plugin-fbt/package.json#L14

### In [npm](https://unpkg.com/babel-plugin-fbt@0.9.1/package.json):

![image](https://user-images.githubusercontent.com/4661784/58783979-f1f94f00-85ea-11e9-9d9a-97601071377e.png)

### Result this problem:
```sh
node ../node_modules/babel-plugin-fbt/bin/collectFBT.js 


internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fbjs/lib/invariant'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/i/all-work/synergeto/node_modules/babel-plugin-fbt/fbt-shift-enums.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by jrwats** [comment]
@retyui, this should be fixed with 0.9.12.  Please reopen if not.

**Comment by retyui** [comment]
I do not see any version witch look like 0.9.12 :

![Screenshot_20190705-000614](https://user-images.githubusercontent.com/4661784/60687697-e5516a80-9eb8-11e9-92b5-5c122cccf8c9.jpg)

**Comment by jrwats** [comment]
Sorry that was the npm module I was referring to
https://www.npmjs.com/package/babel-plugin-fbt
and `babel-plugin-fbt` specifically
