### ISSUE TITLE
JSX Support short bool syntax

### ISSUE THREAD

**Issue by retyui** [facebookincubator/fbt#78]
For next example
```js
<fbt desc="" doNotExtract>Test</fbt>
```

I get this error:
```sh
    TypeError: Cannot read property 'type' of null

      at node_modules/babel-plugin-fbt/FbtUtil.js:140:15
          at Array.forEach (<anonymous>)
      at getOptionsFromAttributes (node_modules/babel-plugin-fbt/FbtUtil.js:130:18)
      at PluginPass.JSXElement (node_modules/babel-plugin-fbt/index.js:153:13)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
```

```js
// this example work fine
<fbt desc="" doNotExtract={true}>Test</fbt>
```

```json
{
    "babel-plugin-fbt": "^0.9.14",
}
```

**Comment by jrwats** [comment]
It's valid JSX, we probably ought to support it.

**Comment by retyui** [comment]
The same problem:

```js
  <fbt:param name="name" number>{person.getName()}</fbt:param>
```

**Comment by retyui** [comment]
I do not know how run tests )

**Comment by jrwats** [comment]
Standby @retyui, we'll support tests "soon" cc @w1106c 
https://github.com/facebookincubator/fbt/pull/86

**Comment by jrwats** [comment]
OK, you are clear for takeoff :)
https://github.com/facebookincubator/fbt/issues/84

Try running `yarn test` from the top-level repo after rebasing

I'd recommend adding some tests using your new syntax similar to:
https://github.com/facebookincubator/fbt/blob/9963128994dadbf1f8c362ee13e313f66787df0e/packages/babel-plugin-fbt/__tests__/fbtJsx-test.js#L870-L881

**Comment by jrwats** [comment]
https://github.com/facebookincubator/fbt/commit/8ba8802f3897b1f984ae56c85fe631e0a7c845a2
