### ISSUE TITLE
The translate script is flaky

### ISSUE THREAD

**Issue by abettadapur** [facebookincubator/fbt#79]
Sometimes, calling the translate script produces the following error: 
```
  Error: EAGAIN: resource temporarily unavailable, read
  at Object.readSync (fs.js:498:3)
  at tryReadSync (fs.js:332:20)
  at Object.readFileSync (fs.js:369:19)
  at Object.<anonymous> (/node_modules/babel-plugin-fbt/bin/translate.js:209:31)
```

**Comment by jrwats** [comment]
Fixed in commit https://github.com/facebookincubator/fbt/commit/b0247c68309b5892869a800c4c31eae74d3469f8
